### ISSUE TITLE
go get generates 1 error

### ISSUE THREAD

**Issue by julbr** [grokify/gotilla#1]
`$go get github.com/grokify/gotilla...` results in:
```
# github.com/grokify/gmp
../github.com/grokify/gmp/int.go:14:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
1 error generated.
```

**Comment by grokify** [comment]
This is likely occurring because you don't have GMP installed.

https://gmplib.org/

I'm working on removing this dependency.

**Comment by grokify** [comment]
Try it now. I replaced the GMP dependency with a pure Go implementation. There's no longer a dependency on GMP.

**Comment by grokify** [comment]
Closing now. Please post if this is still an issue.

**Comment by julbr** [comment]
Your fix worked @grokify - thanks a lot!
